### ISSUE TITLE
Problems with Fedora Kernel 4.12 and higher

### ISSUE THREAD

**Issue by lalbers** [dracut-crypt-ssh/dracut-crypt-ssh#11]
Get following Problem on Fedora Server with Kernel 4.12 and higher:

```
Could not open luks-94200f99-3f4b-432c-9ea2-e58db8a90518 (/dev/disk/by-uuid/94200f99-3f4b-432c-9ea2-e58db8a90518)
```
Doesn't work neither via ssh nor via local terminal
With 4.11 and below it works fine.

**Comment by hurricanehrndz** [comment]
This is because the dracut module `/usr/lib/dracut/modules.d/90crypt` no longer installs `cryptsetup`
in the initrd image. If you create your own module that install the cryptsetup binary into the initrd image it should resolve your issue.

**Comment by tr1cks** [comment]
I have problem with cryptsetup too, but looks like not totally the same. I can login locally, but when I try to do it remotely I get messages:

[FAILED] Failed to start Cryptography Setup ...a1238-7b58-422b-8273-68ef4361472a. See 'systemctl status "systemd-cryptset...\x2d68ef4361472a.service"' for details.
[DEPEND] Dependency failed for Local Encrypted Volumes.

I already add cryptsetup to 60crypt-ssh/module-setup.sh at "dracut_install cryptsetup pkill setterm /lib64/libnss_files.so.2", but it give me nothing. I will be grateful for any advice.

**Comment by tr1cks** [comment]
Tried fresh install of Fedora 26 on VitualBox with all updates and looks like everything work fine. I expect other result...

**Comment by tr1cks** [comment]
Now it works even on my target hardware machine. But only with console_auth through interactive shell. When I try to use unlock, I get "Warning: Unable to lock memory, are you root?" every time.

**Comment by rbu** [comment]
I cannot reproduce the kernel issue the original reporter mentioned. The root lock warning has (unfortunately) been around forever, it should probably just be removed.

**Comment by rbu** [comment]
Please reopen if you can reproduce the issue.

**Comment by tr1cks** [comment]
Can you say few words more about root lock warning? It's looks like not just warning, because luks not unlocked after it.

**Comment by rbu** [comment]
The `unlock` executable tries to `mlock()` memory, meaning RAM contents cannot be written to swap. I'm not sure why that function call fails, but the error does not abort the program (it just continues). It's not critical either because the initramfs has no swap enabled in the first place.

Regarding your bug: Are you saying that `console_auth` works (you enter your password, boot continues), but `unlock` does not? If that is still the case, please reopen the issue and let's debug further. How do you produce the input to `unlock`? Are you using echo (make sure to remove the trailing newline with `echo -n`)?

**Comment by Heidistein** [comment]
This exactly is what is happening to me. 
One machine (centos7) works perfect, 
Other machine (fedora 28 fresh install) wont work with unlock.
Same unlock script, same password. The console_auth command, with the -pasted- password will unlock.
