### ISSUE TITLE
OpenSSH keys from CentOS 8 ssh-keygen fail to convert with dropbearconvert

### ISSUE THREAD

**Issue by konstantinblaesi** [dracut-crypt-ssh/dracut-crypt-ssh#39]
I installed dropbear from source, since it's not available via epel yet  and it was not able to convert the keys. Dracut logs a message regarding that failure during initramfs generation.
I wrote to the dropbear mailinglist regarding that issue, but I think I want to use openssh instead of dropbear in the future. I'll probably just start using https://github.com/gsauthof/dracut-sshd/issues from now on unless I have issues with that one :)

**Comment by Skirmisher** [comment]
I believe this is caused by a change in dropbear. See [this issue on the Arch tracker](https://bugs.archlinux.org/task/60523). Generating the keys in the PEM format as described [here](https://github.com/random-archer/mkinitcpio-systemd-tool/issues/17) allowed `dropbearconvert` to work properly.

Why the module works like this instead of asking the user to generate dropbear-format keys in the first place using `dropbearkey`, I can't say. It makes sense to expect the keys to be in OpenSSH format when configured with `SYSTEM` as the host key source, but not as much when particular keys are specified, IMO.

**Comment by torvitas** [comment]
On fedora 31 the solution over [here](https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/34#issuecomment-510599761) worked, while ```ssh-keygen -A -m PEM``` did ***not*** seem to work.

**Comment by artem-sidorenko** [comment]
https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/43

**Comment by SatoriHoshiAiko** [comment]
I had this same issue. I had to refer to this:

https://developers.yubico.com/PIV/Guides/Generating_keys_using_OpenSSL.html

ssh-keygen - m PEM does NOT work. The OpenSSL does however print a .pem and you can export a .pem.pub for dracut to properly dropbearconvert.

The downside is no password is used for -i private key at ssh time. But given that I am decrypting a Luks partition, this is not a huge security risk.

Unfortunately dropper has made poor choices on enforcing the .pem format, and ask-keygen is not keeping up to properly implementing the .pem format.

Personally, dropper needs to fix this, as they have added less security for the false implication of more security.

OpenSSL can make a proper rsa format, others can use the link I provided above to create an rsa .pem key.

Maybe not inputting a password for the private key is easier anyway.

At the moment no other key types work, and ssh-keygen will not create the pem for dropbearconvert, so Dracut will not work at the moment without using the OpenSSL key format.

Heads up, Dracut is in non working condition, I am on CentOS 7.

Otherwise still great using a non-password OpenSSL .pem key.

Thanks

**Comment by SatoriHoshiAiko** [comment]
Permission Denied (public key) - On all key formats. I even tried OpenSSL. ssh-keygen -m PEM, not working.

This is an issue with dropbear, but nothing is working with dracut.

**Comment by ahesford** [comment]
I think you're conflating a few issues here. This issue regards a failure to generate host keys, but a "Permission denied (public key)" error client-side is caused by mismatched or missing authorized user keys.

In any case, the host key problem isn't an issue with this module. The following works as expected to generate dropbear host keys, even with newer tooling:

```sh
for type in ecdsa rsa ed25519; do
ssh-keygen -t $type -f ${type}.ssh -q -N "" -m PEM
dropbearconvert openssh dropbear ${type}.ssh ${type}.dropbear
done
```

Hence, there is no incompatibility with PEM output and dropbearconvert.

**Comment by SatoriHoshiAiko** [comment]
Alright thank-you.

I’ll try a new set of keys using sshkeygen the way you’ve mentioned.

Dropbear was known to require change to pem outform and not all my keys
were working with dropbearconvert. I was able to reproduce this bug which
is related to dropbear.

I could use new host keys the problem is wanting to use my existing key
that I use on other servers.

But you are right, the issue is with generating keys and with dropbear,
dracut is working as intended.

I’ll give those flags a go and see if I can generate a new key in the
format you suggested.

Thanks

**Comment by konstantinblaesi** [comment]
Personally I have stopped using this module since I found https://github.com/gsauthof/dracut-sshd which works better for me  because it
* uses openssh (less friction between host and initramfs)
* uses systemd
