### ISSUE TITLE
rpm package support

### ISSUE THREAD

**Issue by qtlin** [dracut-crypt-ssh/dracut-crypt-ssh#64]
A pointer to RPM build has been removed from README file, conversation https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/commit/24b1c63e2621a34dfc06ab6f52f6c7237aedb1fa has been very rudely blocked so I am forced to post here.
[Fedora COPR page](https://copr.fedorainfracloud.org/coprs/rbu/dracut-crypt-ssh/) still up, package is being rebuild automatically with every release and contact link points here.

Question: is building from source by clone, make, make install is the only supported option from now on?

**Comment by ahesford** [comment]
https://github.com/dracut-crypt-ssh/dracut-crypt-ssh/issues/62

Comments on the commit were blocked because I found the your comment inconsiderate. This is a volunteer project and we don't have any active Red Hat experience to resolve the key issues. We are not obligated to provide perpetual support for features that you value.

As I noted when I responded to your demand, you are welcome to PR text in the README that documents infrastructure that you wish to maintain to provide RPMs without causing verification failures for users. In the absence of a proposed fix, we are not interested in further comments.

**Comment by qtlin** [comment]
A [project](https://copr.fedorainfracloud.org/coprs/rbu/dracut-crypt-ssh/) points to this location and provides no other details. If not supported please contact the rbu to have it removed to avoid future confusions.
I repeat my question: is building from source by clone, make, make install is the only supported option from now on?

**Comment by uriesk** [comment]
@qtlin i forked the COPR repo and also built from the current master branch

```sh
dnf copr enable uriesk/dracut-crypt-ssh
dnf install dracut-crypt-ssh
```
